version: "3"
services:
  clip-service:
    container_name: ${PROJECT_NAME}_service
    build: .
    environment:
      - CLIP_DATA_DIRECTORY=${CLIP_DATA_DIRECTORY}
    ports:
      - ${PORT}:5000
    volumes:
      - ./data:/workdir/data
      - ./precomputedFeatures:/precomputedFeatures
      - ./src:/workdir/src