version: "3"
services:
  jobs:
    container_name: ${PROJECT_NAME}_service
    build: .
    volumes:
      - ./data:/workdir/data
      - ./precomputedFeatures:/precomputedFeatures
      - ./src:/workdir/src